# Generated by Django 6.0 on 2025-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('calories_per_100g', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
