# Generated by Django 5.0 on 2026-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
        migrations.AddField(
            model_name='food',
            name='default_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='grams_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
