# Generated by Django 5.0 on 2026-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_food_unit_food_default_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='grams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
