version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=health_app_db
      - POSTGRES_USER=health_app_user
      - POSTGRES_PASSWORD=712456Nwokolo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U health_app_user -d health_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://health_app_user:712456Nwokolo@db:5432/health_app_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # React Frontend
  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
